server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

planning.morning.start=09:00
planning.morning.end=12:00
planning.afternoon.start=14:00
planning.afternoon.end=18:00
planning.duration.minutes=60
planning.salles=S4A,S5A,S16A,S17A,AMPHI A,S7A